name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker login 
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login \
          --username "${{ secrets.DOCKER_USERNAME }}" \
          --password-stdin
      - run: docker build -t miodragcdocker/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true miodragcdocker/react-test npm test